import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const sb = createClient(
  'https://gtwvtgynnguiizepzfpu.supabase.co',
  'sb_publishable_wM7la1ds3BUugE634awmHg_Tcpe4wF-',
  { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } }
);
const SITE='https://alemao-erp.github.io/alemao-erp1/';
let db={products:[],clients:[],suppliers:[],sales:[],saleItems:[],cash:[],purchases:[],purchaseItems:[],payable:[],receivable:[],fixed:[]};
const $=id=>document.getElementById(id);
const num=v=>Number(v||0);
const money=v=>num(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const payLabel=v=>({cash:'Dinheiro',pix:'Pix',debit:'Débito',credit:'Crédito',bank_transfer:'Transferência',boleto:'Boleto',other:'Fiado/Outro'}[v]||v||'-');
const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();

function msg(text,error=false){const el=$('status');el.textContent=text;el.style.color=error?'var(--bad)':'var(--ok)';el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),6500)}
function table(rows,headers,fn){if(!rows.length)return '<div class="muted pad">Nenhum registro.</div>';return `<div class="tablewrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${fn(r).map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function isOverdue(r){return r.status==='open'&&r.due_date&&new Date(r.due_date+'T23:59:59')<new Date()}

async function loginPassword(e){e.preventDefault();const {data,error}=await sb.auth.signInWithPassword({email:$('loginEmail').value,password:$('loginPassword').value});if(error){$('loginStatus').textContent=error.message;$('loginStatus').classList.remove('hidden');return}openApp(data.session)}
async function sendMagicLink(){const {error}=await sb.auth.signInWithOtp({email:$('loginEmail').value,options:{emailRedirectTo:SITE,shouldCreateUser:false}});$('loginStatus').textContent=error?error.message:'Link enviado.';$('loginStatus').classList.remove('hidden')}
async function logout(){await sb.auth.signOut();location.reload()}
function openApp(s){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userEmail').textContent=s.user.email;loadAll();show('dashboard')}

async function loadAll(){
  const names=['products','clients','suppliers','sales','sale_items','cash_transactions','purchases','purchase_items','accounts_payable','accounts_receivable','fixed_costs'];
  const rs=await Promise.all(names.map(n=>sb.from(n).select('*')));
  const err=rs.find(r=>r.error)?.error;if(err)return msg('Erro ao carregar: '+err.message,true);
  [db.products,db.clients,db.suppliers,db.sales,db.saleItems,db.cash,db.purchases,db.purchaseItems,db.payable,db.receivable,db.fixed]=rs.map(r=>r.data||[]);
  render();refreshSelects();
}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');$('title').textContent={dashboard:'Dashboard',vendas:'Vendas',produtos:'Produtos',estoque:'Estoque',clientes:'Clientes',fornecedores:'Fornecedores',compras:'Compras',caixa:'Caixa',contas:'Contas',relatorios:'Relatórios'}[id];if(id==='vendas'&&!$('saleLines').children.length)addSaleLine();if(id==='compras'&&!$('purchaseLines').children.length)addPurchaseLine();render();refreshSelects()}
function refreshSelects(){
  $('saleClient').innerHTML='<option value="">Cliente balcão</option>'+db.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
  $('stockProduct').innerHTML=db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
  $('purchaseSupplier').innerHTML='<option value="">Sem fornecedor</option>'+db.suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
  document.querySelectorAll('.sale-prod,.purchase-prod').forEach(sel=>sel.innerHTML=db.products.map(p=>`<option value="${p.id}">${esc(p.name)} — estoque ${num(p.stock)}</option>`).join(''));
}

async function uploadReceipt(file,prefix='comprovante'){
  if(!file)return null;
  if(file.size>10*1024*1024)throw new Error('O comprovante deve ter no máximo 10 MB.');
  const {data:{user}}=await sb.auth.getUser();
  const safe=(file.name||'arquivo').replace(/[^a-zA-Z0-9._-]/g,'_');
  const path=`${user.id}/${prefix}-${Date.now()}-${safe}`;
  const {error}=await sb.storage.from('receipts').upload(path,file,{upsert:false,contentType:file.type||undefined});
  if(error)throw error;return path;
}
async function viewReceipt(path){if(!path)return msg('Nenhum comprovante anexado.',true);const {data,error}=await sb.storage.from('receipts').createSignedUrl(path,120);if(error)return msg(error.message,true);window.open(data.signedUrl,'_blank','noopener')}
async function chooseAndAttach(tableName,id){const inp=document.createElement('input');inp.type='file';inp.accept='image/*,application/pdf';inp.onchange=async()=>{if(!inp.files?.[0])return;try{const path=await uploadReceipt(inp.files[0],tableName);const {error}=await sb.from(tableName).update({receipt_path:path}).eq('id',id);if(error)throw error;await loadAll();msg('Comprovante anexado com sucesso.')}catch(e){msg('Erro no comprovante: '+e.message,true)}};inp.click()}

async function pickContacts(){if(!navigator.contacts?.select)return msg('Seu navegador não permite importar contatos. Teste no Chrome do Android.',true);try{const r=await navigator.contacts.select(['name','tel'],{multiple:true});if(!r?.length)return;const rows=[];for(const c of r){const name=c.name?.[0]?.trim()||'';const phone=c.tel?.[0]?.trim()||'';if(!name)continue;const dup=db.clients.some(x=>(phone&&String(x.phone||'').replace(/\D/g,'')===phone.replace(/\D/g,''))||normalize(x.name)===normalize(name));if(!dup)rows.push({name,phone:phone||null,notes:'Importado dos contatos do celular'})}if(!rows.length)return msg('Os contatos escolhidos já parecem cadastrados.',true);const {error}=await sb.from('clients').insert(rows);if(error)return msg(error.message,true);await loadAll();show('clientes');msg(`${rows.length} contato(s) importado(s).`)}catch(e){if(e?.name!=='AbortError')msg('Não foi possível importar: '+e.message,true)}}

async function addProduct(e){e.preventDefault();const row={name:$('pName').value.trim(),category:$('pCategory').value.trim()||null,cost:num($('pCost').value),price:num($('pPrice').value),stock:num($('pStock').value),min_stock:num($('pMin').value)};const {data,error}=await sb.from('products').insert(row).select().single();if(error)return msg(error.message,true);if(row.stock)await sb.from('stock_moves').insert({product_id:data.id,move_type:'in',quantity:row.stock,reason:'Estoque inicial'});e.target.reset();await loadAll();show('produtos');msg('Produto cadastrado.')}
async function editProduct(id){const p=db.products.find(x=>x.id===id);if(!p)return;const name=prompt('Produto',p.name);if(name===null)return;const category=prompt('Categoria',p.category||'');if(category===null)return;const cost=prompt('Custo',p.cost);if(cost===null)return;const price=prompt('Preço de venda',p.price);if(price===null)return;const min=prompt('Estoque mínimo',p.min_stock);if(min===null)return;const {error}=await sb.from('products').update({name:name.trim(),category:category||null,cost:num(cost),price:num(price),min_stock:num(min)}).eq('id',id);if(error)return msg(error.message,true);await loadAll();show('produtos');msg('Produto atualizado.')}
async function deleteProduct(id){const p=db.products.find(x=>x.id===id);if(!confirm(`Excluir "${p?.name||''}"? Produtos usados em vendas/compras antigas podem impedir a exclusão.`))return;const {error}=await sb.from('products').delete().eq('id',id);if(error)return msg('Não foi possível excluir: '+error.message,true);await loadAll();show('produtos');msg('Produto excluído.')}
async function addClient(e){e.preventDefault();const {error}=await sb.from('clients').insert({name:$('cName').value.trim(),phone:$('cPhone').value.trim()||null,location:$('cLocation').value.trim()||null,notes:$('cNotes').value.trim()||null});if(error)return msg(error.message,true);e.target.reset();await loadAll();show('clientes');msg('Cliente cadastrado.')}
async function editClient(id){const c=db.clients.find(x=>x.id===id);if(!c)return;const name=prompt('Nome',c.name);if(name===null)return;const phone=prompt('Telefone',c.phone||'');if(phone===null)return;const location=prompt('Bairro/Cidade',c.location||'');if(location===null)return;const notes=prompt('Observações',c.notes||'');if(notes===null)return;const {error}=await sb.from('clients').update({name,phone:phone||null,location:location||null,notes:notes||null}).eq('id',id);if(error)return msg(error.message,true);await sb.from('sales').update({client_name:name}).eq('client_id',id);await loadAll();show('clientes');msg('Cliente atualizado.')}
async function deleteClient(id){const c=db.clients.find(x=>x.id===id);if(!confirm(`Excluir o cliente "${c?.name||''}"?`))return;await sb.from('sales').update({client_id:null}).eq('client_id',id);await sb.from('accounts_receivable').update({client_id:null}).eq('client_id',id);const {error}=await sb.from('clients').delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('clientes');msg('Cliente excluído.')}
function clientHistory(id){const c=db.clients.find(x=>x.id===id);const sales=db.sales.filter(s=>s.client_id===id);const total=sales.reduce((a,s)=>a+num(s.total),0);const items={};sales.forEach(s=>db.saleItems.filter(i=>i.sale_id===s.id).forEach(i=>items[i.product_name]=(items[i.product_name]||0)+num(i.quantity)));const top=Object.entries(items).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([n,q])=>`${n}: ${q}`).join('\n')||'Sem produtos ainda.';alert(`${c?.name||'Cliente'}\nCompras: ${sales.length}\nTotal comprado: ${money(total)}\n\nMais comprados:\n${top}`)}
async function addSupplier(e){e.preventDefault();const {error}=await sb.from('suppliers').insert({name:$('sName').value.trim(),phone:$('sPhone').value.trim()||null,document:$('sDocument').value.trim()||null,notes:$('sNotes').value.trim()||null});if(error)return msg(error.message,true);e.target.reset();await loadAll();show('fornecedores');msg('Fornecedor cadastrado.')}
async function editSupplier(id){const s=db.suppliers.find(x=>x.id===id);if(!s)return;const name=prompt('Nome',s.name);if(name===null)return;const phone=prompt('Telefone',s.phone||'');if(phone===null)return;const document=prompt('Documento',s.document||'');if(document===null)return;const notes=prompt('Observações',s.notes||'');if(notes===null)return;const {error}=await sb.from('suppliers').update({name,phone:phone||null,document:document||null,notes:notes||null}).eq('id',id);if(error)return msg(error.message,true);await sb.from('purchases').update({supplier_name:name}).eq('supplier_id',id);await loadAll();show('fornecedores');msg('Fornecedor atualizado.')}
async function deleteSupplier(id){const s=db.suppliers.find(x=>x.id===id);if(!confirm(`Excluir o fornecedor "${s?.name||''}"?`))return;await sb.from('purchases').update({supplier_id:null}).eq('supplier_id',id);await sb.from('accounts_payable').update({supplier_id:null}).eq('supplier_id',id);const {error}=await sb.from('suppliers').delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('fornecedores');msg('Fornecedor excluído.')}
function supplierHistory(id){const s=db.suppliers.find(x=>x.id===id);const purchases=db.purchases.filter(p=>p.supplier_id===id);const total=purchases.reduce((a,p)=>a+num(p.total),0);alert(`${s?.name||'Fornecedor'}\nCompras registradas: ${purchases.length}\nTotal comprado: ${money(total)}`)}

function addSaleLine(){const d=document.createElement('div');d.className='itemline';d.innerHTML='<select class="sale-prod" onchange="saleChanged(this)"></select><input class="sale-qty" type="number" step=".001" min=".001" value="1" oninput="calcSale()"><input class="sale-price" type="number" step=".01" min="0" oninput="calcSale()"><strong class="sale-sub">R$ 0,00</strong><button class="btn bad sm" type="button" onclick="this.parentElement.remove();calcSale()">X</button>';$('saleLines').appendChild(d);refreshSelects();saleChanged(d.querySelector('.sale-prod'))}
function saleChanged(s){const p=db.products.find(x=>x.id===s.value),l=s.parentElement;if(p)l.querySelector('.sale-price').value=p.price;calcSale()}
function calcSale(){let t=0;document.querySelectorAll('#saleLines .itemline').forEach(l=>{const v=num(l.querySelector('.sale-qty').value)*num(l.querySelector('.sale-price').value);l.querySelector('.sale-sub').textContent=money(v);t+=v});$('saleTotal').textContent='Total: '+money(t)}
async function saveSale(){const lines=[...document.querySelectorAll('#saleLines .itemline')].map(l=>({product_id:l.querySelector('.sale-prod').value,quantity:num(l.querySelector('.sale-qty').value),unit_price:num(l.querySelector('.sale-price').value)}));if(!lines.length)return msg('Adicione um produto.',true);for(const i of lines){const p=db.products.find(x=>x.id===i.product_id);if(!p||i.quantity<=0||i.quantity>num(p.stock))return msg('Confira quantidade/estoque de '+(p?.name||'produto'),true)}const client=db.clients.find(x=>x.id===$('saleClient').value),payment=$('salePayment').value;let total=0,totalCost=0;for(const i of lines){const p=db.products.find(x=>x.id===i.product_id);total+=i.quantity*i.unit_price;totalCost+=i.quantity*num(p.cost)}const {data:sale,error}=await sb.from('sales').insert({client_id:client?.id||null,client_name:client?.name||'Cliente balcão',payment_method:payment,total,total_cost:totalCost,status:'completed'}).select().single();if(error)return msg(error.message,true);for(const i of lines){const p=db.products.find(x=>x.id===i.product_id),ti=i.quantity*i.unit_price,tc=i.quantity*num(p.cost);const r=await sb.from('sale_items').insert({sale_id:sale.id,product_id:p.id,product_name:p.name,quantity:i.quantity,unit_price:i.unit_price,unit_cost:num(p.cost),total:ti,total_cost:tc});if(r.error){await sb.from('sales').delete().eq('id',sale.id);return msg('Erro no item: '+r.error.message,true)}await sb.from('products').update({stock:num(p.stock)-i.quantity}).eq('id',p.id);await sb.from('stock_moves').insert({product_id:p.id,move_type:'out',quantity:i.quantity,reason:'Venda '+sale.id})}if(payment==='other')await sb.from('accounts_receivable').insert({client_id:client?.id||null,description:'Venda '+sale.id,amount:total,status:'open',sale_id:sale.id,payment_method:'other'});else await sb.from('cash_transactions').insert({type:'in',amount:total,description:'Venda '+sale.id,payment_method:payment,reference_id:sale.id});$('saleLines').innerHTML='';await loadAll();addSaleLine();show('vendas');msg('Venda registrada com sucesso.')}
async function editSale(id){const s=db.sales.find(x=>x.id===id);if(!s)return;const clientName=prompt('Cliente',s.client_name||'Cliente balcão');if(clientName===null)return;const payment=prompt('Pagamento: pix, cash, debit, credit, bank_transfer, boleto ou other',s.payment_method||'pix');if(payment===null)return;const client=db.clients.find(c=>normalize(c.name)===normalize(clientName));const {error}=await sb.from('sales').update({client_id:client?.id||null,client_name:clientName.trim()||'Cliente balcão',payment_method:payment}).eq('id',id);if(error)return msg(error.message,true);await sb.from('cash_transactions').update({payment_method:payment}).eq('reference_id',id);await loadAll();show('vendas');msg('Venda atualizada.')}
async function deleteSale(id){const s=db.sales.find(x=>x.id===id);if(!confirm(`Excluir venda de ${money(s?.total)}? O estoque será devolvido.`))return;for(const i of db.saleItems.filter(i=>i.sale_id===id)){const p=db.products.find(x=>x.id===i.product_id);if(p)await sb.from('products').update({stock:num(p.stock)+num(i.quantity)}).eq('id',p.id)}await sb.from('cash_transactions').delete().eq('reference_id',id);await sb.from('accounts_receivable').delete().eq('sale_id',id);await sb.from('sale_items').delete().eq('sale_id',id);const {error}=await sb.from('sales').delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('vendas');msg('Venda excluída e estoque devolvido.')}

async function stockMove(e){e.preventDefault();const p=db.products.find(x=>x.id===$('stockProduct').value),q=num($('stockQty').value),t=$('stockType').value;let n=num(p.stock);if(t==='in')n+=q;else if(t==='out'){if(q>n)return msg('Estoque insuficiente.',true);n-=q}else n=q;const {error}=await sb.from('products').update({stock:n}).eq('id',p.id);if(error)return msg(error.message,true);await sb.from('stock_moves').insert({product_id:p.id,move_type:t,quantity:q,reason:'Movimentação manual'});e.target.reset();await loadAll();show('estoque');msg('Estoque atualizado.')}

function addPurchaseLine(){const d=document.createElement('div');d.className='itemline';d.innerHTML='<select class="purchase-prod" onchange="purchaseChanged(this)"></select><input class="purchase-qty" type="number" step=".001" min=".001" value="1" oninput="calcPurchase()"><input class="purchase-cost" type="number" step=".01" min="0" oninput="calcPurchase()"><strong class="purchase-sub">R$ 0,00</strong><button class="btn bad sm" type="button" onclick="this.parentElement.remove();calcPurchase()">X</button>';$('purchaseLines').appendChild(d);refreshSelects();purchaseChanged(d.querySelector('.purchase-prod'))}
function purchaseChanged(s){const p=db.products.find(x=>x.id===s.value);if(p)s.parentElement.querySelector('.purchase-cost').value=p.cost;calcPurchase()}
function calcPurchase(){let t=0;document.querySelectorAll('#purchaseLines .itemline').forEach(l=>{const v=num(l.querySelector('.purchase-qty').value)*num(l.querySelector('.purchase-cost').value);l.querySelector('.purchase-sub').textContent=money(v);t+=v});$('purchaseTotal').textContent='Total: '+money(t)}
async function savePurchase(){const lines=[...document.querySelectorAll('#purchaseLines .itemline')].map(l=>({product_id:l.querySelector('.purchase-prod').value,quantity:num(l.querySelector('.purchase-qty').value),unit_cost:num(l.querySelector('.purchase-cost').value)}));if(!lines.length)return msg('Adicione o que vai comprar.',true);for(const i of lines)if(!i.product_id||i.quantity<=0)return msg('Confira produto e quantidade.',true);const sup=db.suppliers.find(x=>x.id===$('purchaseSupplier').value),total=lines.reduce((a,i)=>a+i.quantity*i.unit_cost,0),st=$('purchaseStatus').value;let receipt=null;try{receipt=await uploadReceipt($('purchaseReceipt').files?.[0],'compra')}catch(e){return msg(e.message,true)}const {data:purch,error}=await sb.from('purchases').insert({supplier_id:sup?.id||null,supplier_name:sup?.name||null,total,payment_status:st,due_date:$('purchaseDue').value||null,receipt_path:receipt}).select().single();if(error)return msg(error.message,true);for(const i of lines){const p=db.products.find(x=>x.id===i.product_id);const ir=await sb.from('purchase_items').insert({purchase_id:purch.id,product_id:p.id,product_name:p.name,quantity:i.quantity,unit_cost:i.unit_cost,total:i.quantity*i.unit_cost});if(ir.error)return msg('Erro no item da compra: '+ir.error.message,true);await sb.from('products').update({stock:num(p.stock)+i.quantity,cost:i.unit_cost}).eq('id',p.id);await sb.from('stock_moves').insert({product_id:p.id,move_type:'in',quantity:i.quantity,reason:'Compra '+purch.id})}if(st==='paid')await sb.from('cash_transactions').insert({type:'out',amount:total,description:'Compra de mercadoria',payment_method:'other',reference_id:purch.id,receipt_path:receipt});else await sb.from('accounts_payable').insert({supplier_id:sup?.id||null,description:'Compra de mercadoria',amount:total,due_date:$('purchaseDue').value||null,status:'open',purchase_id:purch.id,receipt_path:receipt});$('purchaseLines').innerHTML='';$('purchaseReceipt').value='';await loadAll();addPurchaseLine();show('compras');msg('Compra registrada e estoque atualizado.')}
async function deletePurchase(id){const pch=db.purchases.find(x=>x.id===id);if(!confirm(`Excluir compra de ${money(pch?.total)}? O estoque recebido será retirado.`))return;for(const i of db.purchaseItems.filter(i=>i.purchase_id===id)){const p=db.products.find(x=>x.id===i.product_id);if(p){const novo=Math.max(0,num(p.stock)-num(i.quantity));await sb.from('products').update({stock:novo}).eq('id',p.id)}}await sb.from('cash_transactions').delete().eq('reference_id',id);await sb.from('accounts_payable').delete().eq('purchase_id',id);await sb.from('purchase_items').delete().eq('purchase_id',id);const {error}=await sb.from('purchases').delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('compras');msg('Compra excluída e estoque ajustado.')}
async function editPurchase(id){const p=db.purchases.find(x=>x.id===id);if(!p)return;const supplier=prompt('Fornecedor',p.supplier_name||'');if(supplier===null)return;const status=prompt('Status: paid ou open',p.payment_status||'paid');if(status===null)return;const due=prompt('Vencimento AAAA-MM-DD',p.due_date||'');if(due===null)return;const sup=db.suppliers.find(s=>normalize(s.name)===normalize(supplier));const {error}=await sb.from('purchases').update({supplier_id:sup?.id||null,supplier_name:supplier||null,payment_status:status,due_date:due||null}).eq('id',id);if(error)return msg(error.message,true);await loadAll();show('compras');msg('Compra atualizada. Para alterar itens/quantidades, exclua e refaça a compra.')}

async function addExpense(e){e.preventDefault();let receipt=null;try{receipt=await uploadReceipt($('eReceipt').files?.[0],'despesa')}catch(err){return msg(err.message,true)}const {error}=await sb.from('cash_transactions').insert({type:'out',amount:num($('eAmount').value),description:$('eDesc').value.trim(),payment_method:$('ePay').value,receipt_path:receipt});if(error)return msg(error.message,true);e.target.reset();await loadAll();show('caixa');msg('Despesa registrada.')}
async function addFixedCost(e){e.preventDefault();const {error}=await sb.from('fixed_costs').insert({description:$('fDesc').value.trim(),amount:num($('fAmount').value)});if(error)return msg(error.message,true);e.target.reset();await loadAll();show('contas');msg('Custo fixo adicionado.')}
async function settle(type,id){const tn=type==='receivable'?'accounts_receivable':'accounts_payable',row=(type==='receivable'?db.receivable:db.payable).find(x=>x.id===id);if(!row)return;const withReceipt=confirm('Deseja anexar um comprovante agora?');if(withReceipt){const inp=document.createElement('input');inp.type='file';inp.accept='image/*,application/pdf';inp.onchange=async()=>{if(!inp.files?.[0])return;await finalizeSettle(type,id,inp.files[0])};inp.click()}else await finalizeSettle(type,id,null)}
async function finalizeSettle(type,id,file){const tn=type==='receivable'?'accounts_receivable':'accounts_payable',row=(type==='receivable'?db.receivable:db.payable).find(x=>x.id===id);let receipt=row.receipt_path||null;try{if(file)receipt=await uploadReceipt(file,type)}catch(e){return msg(e.message,true)}const {error}=await sb.from(tn).update({status:type==='receivable'?'received':'paid',[type==='receivable'?'received_at':'paid_at']:new Date().toISOString(),receipt_path:receipt}).eq('id',id);if(error)return msg(error.message,true);await sb.from('cash_transactions').insert({type:type==='receivable'?'in':'out',amount:row.amount,description:row.description,payment_method:row.payment_method||'other',receipt_path:receipt});await loadAll();show('contas');msg('Conta baixada.')}
async function editAccount(type,id){const arr=type==='receivable'?db.receivable:db.payable,row=arr.find(x=>x.id===id);if(!row)return;const description=prompt('Descrição',row.description||'');if(description===null)return;const amount=prompt('Valor',row.amount??0);if(amount===null)return;const due=prompt('Vencimento AAAA-MM-DD',row.due_date||'');if(due===null)return;const tn=type==='receivable'?'accounts_receivable':'accounts_payable';const {error}=await sb.from(tn).update({description,amount:num(amount),due_date:due||null}).eq('id',id);if(error)return msg(error.message,true);await loadAll();show('contas');msg('Conta atualizada.')}
async function deleteAccount(type,id){if(!confirm('Excluir esta conta?'))return;const tn=type==='receivable'?'accounts_receivable':'accounts_payable';const {error}=await sb.from(tn).delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('contas');msg('Conta excluída.')}
async function editFixed(id){const r=db.fixed.find(x=>x.id===id);if(!r)return;const d=prompt('Descrição',r.description||'');if(d===null)return;const a=prompt('Valor mensal',r.amount??0);if(a===null)return;const {error}=await sb.from('fixed_costs').update({description:d,amount:num(a)}).eq('id',id);if(error)return msg(error.message,true);await loadAll();show('contas');msg('Custo fixo atualizado.')}
async function deleteFixed(id){if(!confirm('Excluir este custo fixo?'))return;const {error}=await sb.from('fixed_costs').delete().eq('id',id);if(error)return msg(error.message,true);await loadAll();show('contas');msg('Custo fixo excluído.')}

function filtered(list,inputId,fields){const q=normalize($(inputId)?.value);if(!q)return list;return list.filter(r=>fields.some(f=>normalize(r[f]).includes(q)))}
function render(){
  const now=new Date(),ym=now.toISOString().slice(0,7),salesMonth=db.sales.filter(s=>String(s.sold_at||'').slice(0,7)===ym),rev=salesMonth.reduce((a,s)=>a+num(s.total),0),cmv=salesMonth.reduce((a,s)=>a+num(s.total_cost),0),gross=rev-cmv,ins=db.cash.filter(x=>x.type==='in').reduce((a,x)=>a+num(x.amount),0),outs=db.cash.filter(x=>x.type==='out').reduce((a,x)=>a+num(x.amount),0),fixed=db.fixed.filter(x=>x.active!==false).reduce((a,x)=>a+num(x.amount),0),margin=rev?gross/rev:0,breakEven=margin?fixed/margin:0,stockValue=db.products.reduce((a,p)=>a+num(p.stock)*num(p.cost),0),openRec=db.receivable.filter(x=>x.status==='open').reduce((a,x)=>a+num(x.amount),0),openPay=db.payable.filter(x=>x.status==='open').reduce((a,x)=>a+num(x.amount),0),ticket=salesMonth.length?rev/salesMonth.length:0;
  $('today').textContent=now.toLocaleDateString('pt-BR',{dateStyle:'full'});$('kSales').textContent=money(rev);$('kProfit').textContent=money(gross);$('kCash').textContent=money(ins-outs);$('kBreak').textContent=money(breakEven);$('kTicket').textContent=money(ticket);$('kStockValue').textContent=money(stockValue);$('kReceivable').textContent=money(openRec);$('kPayable').textContent=money(openPay);$('cashIn').textContent=money(ins);$('cashOut').textContent=money(outs);$('cashBal').textContent=money(ins-outs);$('rRevenue').textContent=money(rev);$('rCmv').textContent=money(cmv);$('rGross').textContent=money(gross);$('rMargin').textContent=(margin*100).toFixed(1)+'%';$('rTicket').textContent=money(ticket);$('rSalesCount').textContent=salesMonth.length;$('rStockValue').textContent=money(stockValue);$('rNet').textContent=money(gross-fixed);
  const itemBy={};db.saleItems.forEach(i=>(itemBy[i.sale_id]??=[]).push(i));
  $('lowStock').innerHTML=db.products.filter(p=>num(p.stock)<=num(p.min_stock)).map(p=>`<div>${esc(p.name)} — <span class="badtext">${num(p.stock)}</span></div>`).join('')||'<div class="muted">Tudo certo.</div>';
  const prod={};db.saleItems.forEach(i=>prod[i.product_name]=(prod[i.product_name]||0)+num(i.quantity));const top=Object.entries(prod).sort((a,b)=>b[1]-a[1]).slice(0,8);$('topProducts').innerHTML=top.map(x=>`<div>${esc(x[0])}: ${x[1]}</div>`).join('')||'<div class="muted">Sem vendas.</div>';$('topProductsReport').innerHTML=$('topProducts').innerHTML;
  $('recentSales').innerHTML=[...salesMonth].sort((a,b)=>new Date(b.sold_at)-new Date(a.sold_at)).slice(0,8).map(s=>`<div>${new Date(s.sold_at).toLocaleDateString('pt-BR')} — ${esc(s.client_name||'Cliente balcão')} — ${money(s.total)}</div>`).join('')||'<div class="muted">Sem vendas.</div>';
  const products=filtered(db.products,'productSearch',['name','category']);$('productsTable').innerHTML=table(products,['Produto','Categoria','Custo','Preço','Estoque','Ações'],p=>[esc(p.name),esc(p.category||'-'),money(p.cost),money(p.price),num(p.stock),`<div class="actions"><button class="btn sm" onclick="editProduct('${p.id}')">Editar</button><button class="btn bad sm" onclick="deleteProduct('${p.id}')">Excluir</button></div>`]);
  $('stockTable').innerHTML=table(db.products,['Produto','Estoque','Mínimo','Valor estoque','Situação'],p=>[esc(p.name),num(p.stock),num(p.min_stock),money(num(p.stock)*num(p.cost)),num(p.stock)<=num(p.min_stock)?'<span class="badtext">Comprar</span>':'<span class="ok">OK</span>']);
  const clients=filtered(db.clients,'clientSearch',['name','phone','location']);$('clientsTable').innerHTML=table(clients,['Nome','Telefone','Local','Ações'],c=>[esc(c.name),esc(c.phone||'-'),esc(c.location||'-'),`<div class="actions"><button class="btn sm" onclick="clientHistory('${c.id}')">Histórico</button><button class="btn alt sm" onclick="editClient('${c.id}')">Editar</button><button class="btn bad sm" onclick="deleteClient('${c.id}')">Excluir</button></div>`]);
  const suppliers=filtered(db.suppliers,'supplierSearch',['name','phone','document']);$('suppliersTable').innerHTML=table(suppliers,['Nome','Telefone','Documento','Ações'],s=>[esc(s.name),esc(s.phone||'-'),esc(s.document||'-'),`<div class="actions"><button class="btn sm" onclick="supplierHistory('${s.id}')">Histórico</button><button class="btn alt sm" onclick="editSupplier('${s.id}')">Editar</button><button class="btn bad sm" onclick="deleteSupplier('${s.id}')">Excluir</button></div>`]);
  $('salesTable').innerHTML=table([...db.sales].sort((a,b)=>new Date(b.sold_at)-new Date(a.sold_at)),['Data','Cliente','Itens','Pagamento','Total','Lucro','Ações'],s=>[new Date(s.sold_at).toLocaleDateString('pt-BR'),esc(s.client_name||'Cliente balcão'),esc((itemBy[s.id]||[]).map(i=>i.product_name+' x '+num(i.quantity)).join(', ')||'-'),payLabel(s.payment_method),money(s.total),money(num(s.total)-num(s.total_cost)),`<div class="actions"><button class="btn sm" onclick="editSale('${s.id}')">Editar</button><button class="btn bad sm" onclick="deleteSale('${s.id}')">Excluir</button></div>`]);
  $('cashTable').innerHTML=table([...db.cash].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)),['Data','Tipo','Descrição','Forma','Valor','Comprovante'],x=>[new Date(x.created_at).toLocaleDateString('pt-BR'),x.type==='in'?'<span class="ok">Entrada</span>':'<span class="badtext">Saída</span>',esc(x.description),payLabel(x.payment_method),money(x.amount),x.receipt_path?`<button class="btn alt sm" onclick="viewReceipt('${x.receipt_path}')">Ver</button>`:'-']);
  $('purchasesTable').innerHTML=table([...db.purchases].sort((a,b)=>new Date(b.purchased_at)-new Date(a.purchased_at)),['Data','Fornecedor','Itens','Total','Status','Comprovante','Ações'],p=>[new Date(p.purchased_at).toLocaleDateString('pt-BR'),esc(p.supplier_name||'-'),esc(db.purchaseItems.filter(i=>i.purchase_id===p.id).map(i=>`${i.product_name} x ${num(i.quantity)}`).join(', ')||'-'),money(p.total),esc(p.payment_status),p.receipt_path?`<button class="btn alt sm" onclick="viewReceipt('${p.receipt_path}')">Ver</button>`:`<button class="btn alt sm" onclick="chooseAndAttach('purchases','${p.id}')">Anexar</button>`,`<div class="actions"><button class="btn sm" onclick="editPurchase('${p.id}')">Editar</button><button class="btn bad sm" onclick="deletePurchase('${p.id}')">Excluir</button></div>`]);
  $('receivableTable').innerHTML=table(db.receivable.filter(x=>x.status==='open'),['Descrição','Valor','Venc.','Comprovante','Ações'],x=>[esc(x.description),money(x.amount),isOverdue(x)?`<span class="badtext">${x.due_date} VENCIDA</span>`:(x.due_date||'-'),x.receipt_path?`<button class="btn alt sm" onclick="viewReceipt('${x.receipt_path}')">Ver</button>`:`<button class="btn alt sm" onclick="chooseAndAttach('accounts_receivable','${x.id}')">Anexar</button>`,`<div class="actions"><button class="btn sm" onclick="settle('receivable','${x.id}')">Receber</button><button class="btn alt sm" onclick="editAccount('receivable','${x.id}')">Editar</button><button class="btn bad sm" onclick="deleteAccount('receivable','${x.id}')">Excluir</button></div>`]);
  $('payableTable').innerHTML=table(db.payable.filter(x=>x.status==='open'),['Descrição','Valor','Venc.','Comprovante','Ações'],x=>[esc(x.description),money(x.amount),isOverdue(x)?`<span class="badtext">${x.due_date} VENCIDA</span>`:(x.due_date||'-'),x.receipt_path?`<button class="btn alt sm" onclick="viewReceipt('${x.receipt_path}')">Ver</button>`:`<button class="btn alt sm" onclick="chooseAndAttach('accounts_payable','${x.id}')">Anexar</button>`,`<div class="actions"><button class="btn sm" onclick="settle('payable','${x.id}')">Pagar</button><button class="btn alt sm" onclick="editAccount('payable','${x.id}')">Editar</button><button class="btn bad sm" onclick="deleteAccount('payable','${x.id}')">Excluir</button></div>`]);
  $('fixedTable').innerHTML=table(db.fixed,['Descrição','Valor mensal','Ações'],x=>[esc(x.description),money(x.amount),`<div class="actions"><button class="btn sm" onclick="editFixed('${x.id}')">Editar</button><button class="btn bad sm" onclick="deleteFixed('${x.id}')">Excluir</button></div>`]);
  const cli={};db.sales.forEach(s=>cli[s.client_name||'Cliente balcão']=(cli[s.client_name||'Cliente balcão']||0)+num(s.total));$('topClients').innerHTML=Object.entries(cli).sort((a,b)=>b[1]-a[1]).slice(0,8).map(x=>`<div>${esc(x[0])}: ${money(x[1])}</div>`).join('')||'<div class="muted">Sem vendas.</div>';calcSale();calcPurchase();
}

Object.assign(window,{loginPassword,sendMagicLink,logout,show,pickContacts,addProduct,editProduct,deleteProduct,addClient,editClient,deleteClient,clientHistory,addSupplier,editSupplier,deleteSupplier,supplierHistory,addSaleLine,saleChanged,calcSale,saveSale,editSale,deleteSale,stockMove,addPurchaseLine,purchaseChanged,calcPurchase,savePurchase,editPurchase,deletePurchase,addExpense,addFixedCost,settle,editAccount,deleteAccount,editFixed,deleteFixed,viewReceipt,chooseAndAttach,render});
sb.auth.onAuthStateChange((_,s)=>s?openApp(s):null);const {data:{session}}=await sb.auth.getSession();if(session)openApp(session);
