-- V15 - Saídas sem venda sincronizadas
-- Execute no SQL Editor do Supabase antes de ativar a sincronização completa.
create table if not exists public.stock_outputs (
  id bigint generated by default as identity primary key,
  product_id bigint,
  product_name text not null,
  quantity numeric not null check (quantity > 0),
  unit_cost numeric not null default 0,
  total_cost numeric not null default 0,
  reason text not null,
  output_date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists stock_outputs_output_date_idx on public.stock_outputs(output_date);
create index if not exists stock_outputs_product_id_idx on public.stock_outputs(product_id);

alter table public.stock_outputs enable row level security;

drop policy if exists "authenticated read stock_outputs" on public.stock_outputs;
create policy "authenticated read stock_outputs" on public.stock_outputs for select to authenticated using (true);
drop policy if exists "authenticated insert stock_outputs" on public.stock_outputs;
create policy "authenticated insert stock_outputs" on public.stock_outputs for insert to authenticated with check (true);
drop policy if exists "authenticated update stock_outputs" on public.stock_outputs;
create policy "authenticated update stock_outputs" on public.stock_outputs for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete stock_outputs" on public.stock_outputs;
create policy "authenticated delete stock_outputs" on public.stock_outputs for delete to authenticated using (true);
