(()=>{
'use strict';
const wait=()=>{
  if(typeof DB==='undefined'||typeof $==='undefined'||typeof num==='undefined'||typeof updateRow!=='function'||!document.getElementById('app')) return setTimeout(wait,150);
  setupV6();
};
const alpha=(a,b)=>String(a?.name||'').localeCompare(String(b?.name||''),'pt-BR',{sensitivity:'base',numeric:true});
function sortDB(){['products','clients','suppliers'].forEach(k=>{if(Array.isArray(DB[k]))DB[k].sort(alpha)});}
function style(){if(document.getElementById('v6style'))return;const s=document.createElement('style');s.id='v6style';s.textContent=`
.v6-badge{display:inline-flex;align-items:center;gap:6px;background:#fff7ed;color:#9a3412;border:1px solid #fed7aa;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:700;margin-left:8px}
.v6-costbar{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:12px;padding:12px;margin:12px 0}.v6-summary{background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:10px;margin:10px 0;font-size:13px}.v6-modal-bg{position:fixed;inset:0;background:rgba(17,24,39,.55);display:grid;place-items:center;z-index:9999;padding:18px}.v6-modal{background:#fff;border-radius:16px;width:min(720px,100%);max-height:92vh;overflow:auto;padding:20px;box-shadow:0 24px 80px rgba(0,0,0,.25)}.v6-modal h3{margin-top:0}.v6-modal .grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.v6-modal label{display:block;font-size:12px;color:#667085;margin-bottom:5px}.v6-modal input{width:100%;padding:10px;border:1px solid #d0d5dd;border-radius:8px}.v6-modal .foot{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.v6-line{grid-template-columns:2fr .65fr 1fr 1fr auto!important}.v6-help{font-size:12px;color:#667085;margin-top:4px}
@media(max-width:760px){.v6-costbar{grid-template-columns:1fr 1fr}.v6-modal .grid{grid-template-columns:1fr}.v6-line{grid-template-columns:1fr!important}}
`;document.head.appendChild(s)}
function badge(){const b=document.querySelector('.brand small');if(b)b.textContent='ERP V6 • Profissional';}
function installSort(){
  const oldLoad=window.load;
  if(typeof oldLoad==='function'&&!oldLoad.__v6){const wrapped=async function(){const r=await oldLoad.apply(this,arguments);sortDB();if(typeof renderAll==='function')renderAll();return r};wrapped.__v6=true;window.load=wrapped;}
  sortDB();
  const oldRefresh=window.refreshSelects;
  if(typeof oldRefresh==='function'&&!oldRefresh.__v6){const wrapped=function(){sortDB();return oldRefresh.apply(this,arguments)};wrapped.__v6=true;window.refreshSelects=wrapped;}
}
function installProductEditor(){
  if(!document.getElementById('v6ProductModal')){const d=document.createElement('div');d.id='v6ProductModal';d.className='v6-modal-bg hidden';d.innerHTML=`<div class="v6-modal"><h3>Editar produto</h3><input id="v6Pid" type="hidden"><div class="grid"><div><label>Nome do produto</label><input id="v6PName"></div><div><label>Categoria</label><input id="v6PCat"></div><div><label>Custo atual (R$)</label><input id="v6PCost" type="number" step="0.01"></div><div><label>Preço de venda (R$)</label><input id="v6PPrice" type="number" step="0.01"></div><div><label>Estoque atual</label><input id="v6PStock" type="number" step="0.001"></div><div><label>Estoque mínimo</label><input id="v6PMin" type="number" step="0.001"></div></div><div class="v6-help">Você pode alterar todos os valores do cadastro por esta tela.</div><div class="foot"><button class="btn alt" id="v6PCancel">Cancelar</button><button class="btn" id="v6PSave">Salvar alterações</button></div></div>`;document.body.appendChild(d);$('v6PCancel').onclick=()=>d.classList.add('hidden');$('v6PSave').onclick=async()=>{try{const id=$('v6Pid').value;await updateRow('products',id,{name:$('v6PName').value.trim(),category:$('v6PCat').value.trim()||null,cost:num($('v6PCost').value),price:num($('v6PPrice').value),stock:num($('v6PStock').value),min_stock:num($('v6PMin').value)});d.classList.add('hidden');await load();if(typeof msg==='function')msg('Produto atualizado com sucesso.')}catch(e){if(typeof msg==='function')msg('Erro ao atualizar produto: '+e.message,true)}};}
  window.editProduct=function(id){const p=(DB.products||[]).find(x=>String(x.id)===String(id));if(!p)return;$('v6Pid').value=p.id;$('v6PName').value=p.name||'';$('v6PCat').value=p.category||'';$('v6PCost').value=num(p.cost).toFixed(2);$('v6PPrice').value=num(p.price).toFixed(2);$('v6PStock').value=num(p.stock);$('v6PMin').value=num(p.min_stock);$('v6ProductModal').classList.remove('hidden')};
}
function ensurePurchaseCosts(){
  const page=$('compras');if(!page||$('purchaseTransport'))return;
  const panel=page.querySelector('.panel');const lines=$('purchaseLines');if(!panel||!lines)return;
  const box=document.createElement('div');box.className='v6-costbar';box.innerHTML=`<div class="field"><label>Frete / transporte (R$)</label><input id="purchaseTransport" type="number" step="0.01" min="0" value="0"></div><div class="field"><label>Outros custos (R$)</label><input id="purchaseOther" type="number" step="0.01" min="0" value="0"></div><div class="field"><label>Observação da compra</label><input id="purchaseV6Notes" placeholder="Ex.: pedágio, embalagem, taxa"></div><div class="field"><label>Regra de custo</label><div class="v6-help">Frete e outros custos são rateados entre os produtos e incorporados ao custo real.</div></div>`;panel.insertBefore(box,lines);$('purchaseTransport').oninput=calcPurchase;$('purchaseOther').oninput=calcPurchase;
  const sum=document.createElement('div');sum.id='v6PurchaseSummary';sum.className='v6-summary';lines.parentNode.insertBefore(sum,lines.nextSibling);
}
function installPurchase(){
  ensurePurchaseCosts();
  window.addPurchaseLine=function(item=null){const d=document.createElement('div');d.className='itemline v6-line';d.innerHTML='<div><label class="muted">Produto</label><select class="purchase-prod"></select></div><div><label class="muted">Qtd.</label><input class="purchase-qty" type="number" step=".001" min=".001" value="1"></div><div><label class="muted">Preço de compra / un.</label><input class="purchase-cost" type="number" step=".01" min="0"></div><div><label class="muted">Preço de venda</label><input class="purchase-sale" type="number" step=".01" min="0"></div><button class="btn bad sm" type="button">X</button>';$('purchaseLines').appendChild(d);if(typeof refreshSelects==='function')refreshSelects();const sel=d.querySelector('.purchase-prod'),qty=d.querySelector('.purchase-qty'),cost=d.querySelector('.purchase-cost'),sale=d.querySelector('.purchase-sale');sel.onchange=()=>{const p=(DB.products||[]).find(x=>String(x.id)===String(sel.value));if(p){cost.value=num(p.cost).toFixed(2);sale.value=num(p.price).toFixed(2)}calcPurchase()};qty.oninput=cost.oninput=sale.oninput=calcPurchase;d.querySelector('button').onclick=()=>{d.remove();calcPurchase()};if(item){sel.value=item.product_id;qty.value=item.quantity;cost.value=item.unit_cost;sale.value=item.sale_price||((DB.products||[]).find(x=>String(x.id)===String(item.product_id))?.price||0)}else sel.onchange();calcPurchase()};
  window.purchaseDraft=function(){const items=[...document.querySelectorAll('#purchaseLines .itemline')].map(d=>({product_id:d.querySelector('.purchase-prod').value,quantity:num(d.querySelector('.purchase-qty').value),unit_cost:num(d.querySelector('.purchase-cost').value),sale_price:num(d.querySelector('.purchase-sale')?.value)})).filter(x=>x.product_id&&x.quantity>0);const merchandise=items.reduce((a,i)=>a+i.quantity*i.unit_cost,0),transport=num($('purchaseTransport')?.value),other=num($('purchaseOther')?.value),extras=transport+other,total=merchandise+extras;items.forEach(i=>{const line=i.quantity*i.unit_cost,share=merchandise>0?line/merchandise:1/Math.max(items.length,1);i.allocated_extra=extras*share;i.landed_unit_cost=i.unit_cost+(i.quantity?i.allocated_extra/i.quantity:0)});return{items,merchandise,transport,other,extras,total}};
  window.calcPurchase=function(){const d=purchaseDraft();if($('purchaseTotal'))$('purchaseTotal').textContent='Total da compra: '+money(d.total);if($('v6PurchaseSummary'))$('v6PurchaseSummary').innerHTML='<b>Mercadorias:</b> '+money(d.merchandise)+' &nbsp; • &nbsp; <b>Frete:</b> '+money(d.transport)+' &nbsp; • &nbsp; <b>Outros:</b> '+money(d.other)+' &nbsp; • &nbsp; <b>Custo total:</b> '+money(d.total)};
  window.savePurchase=async function(){const d=purchaseDraft();if(!d.items.length)return msg('Adicione ao menos um produto.',true);try{const s=(DB.suppliers||[]).find(x=>String(x.id)===String($('purchaseSupplier').value)),date=$('purchaseDate').value?new Date($('purchaseDate').value).toISOString():new Date().toISOString(),receipt=typeof uploadReceipt==='function'?await uploadReceipt($('purchaseReceipt').files[0],'compra'):null,row={supplier_id:s?.id||null,supplier_name:s?.name||null,payment_status:$('purchaseStatus').value,due_date:$('purchaseDue').value||null,total:d.total,purchased_at:date};if(receipt)row.receipt_path=receipt;const meta={transport:d.transport,other:d.other,notes:$('purchaseV6Notes')?.value||''};if(window.editingPurchase){for(const old of (DB.purchase_items||[]).filter(i=>String(i.purchase_id)===String(window.editingPurchase))){const p=(DB.products||[]).find(x=>String(x.id)===String(old.product_id));if(p)await updateRow('products',p.id,{stock:num(p.stock)-num(old.quantity)})}await req('/rest/v1/purchase_items?purchase_id=eq.'+encodeURIComponent(window.editingPurchase),{method:'DELETE'});await updateRow('purchases',window.editingPurchase,row);for(const i of d.items){const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));await insert('purchase_items',{purchase_id:window.editingPurchase,product_id:p.id,product_name:p.name,quantity:i.quantity,unit_cost:i.unit_cost});await updateRow('products',p.id,{stock:num(p.stock)+i.quantity,cost:Number(i.landed_unit_cost.toFixed(4)),price:i.sale_price>0?i.sale_price:num(p.price)})}localStorage.setItem('erp_purchase_meta_'+window.editingPurchase,JSON.stringify(meta))}else{const created=(await insert('purchases',row))[0];for(const i of d.items){const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));await insert('purchase_items',{purchase_id:created.id,product_id:p.id,product_name:p.name,quantity:i.quantity,unit_cost:i.unit_cost});await updateRow('products',p.id,{stock:num(p.stock)+i.quantity,cost:Number(i.landed_unit_cost.toFixed(4)),price:i.sale_price>0?i.sale_price:num(p.price)})}localStorage.setItem('erp_purchase_meta_'+created.id,JSON.stringify(meta))}resetPurchase();await load();go('compras');msg('Compra salva. Estoque, custo real e preço de venda atualizados.')}catch(e){msg('Erro ao salvar compra: '+e.message,true)}};
  const oldEdit=window.editPurchase;window.editPurchase=function(id){oldEdit(id);setTimeout(()=>{ensurePurchaseCosts();let m={transport:0,other:0,notes:''};try{m=JSON.parse(localStorage.getItem('erp_purchase_meta_'+id)||'{}')}catch{}$('purchaseTransport').value=m.transport||0;$('purchaseOther').value=m.other||0;$('purchaseV6Notes').value=m.notes||'';document.querySelectorAll('#purchaseLines .itemline').forEach(line=>{if(!line.querySelector('.purchase-sale')){const p=(DB.products||[]).find(x=>String(x.id)===String(line.querySelector('.purchase-prod')?.value));const wrap=document.createElement('div');wrap.innerHTML='<label class="muted">Preço de venda</label><input class="purchase-sale" type="number" step=".01" min="0" value="'+num(p?.price).toFixed(2)+'">';line.insertBefore(wrap,line.lastElementChild);line.classList.add('v6-line');wrap.querySelector('input').oninput=calcPurchase}});calcPurchase()},0)};
  const oldReset=window.resetPurchase;window.resetPurchase=function(){oldReset();ensurePurchaseCosts();if($('purchaseTransport'))$('purchaseTransport').value=0;if($('purchaseOther'))$('purchaseOther').value=0;if($('purchaseV6Notes'))$('purchaseV6Notes').value='';calcPurchase()};
  if($('addPurchaseLine'))$('addPurchaseLine').onclick=()=>addPurchaseLine();if($('savePurchase'))$('savePurchase').onclick=savePurchase;if($('cancelPurchase'))$('cancelPurchase').onclick=resetPurchase;
  if($('purchaseLines')){$('purchaseLines').innerHTML='';addPurchaseLine()}
}
function professionalTables(){
  const oldRP=window.renderProducts;if(typeof oldRP==='function'){window.renderProducts=function(){sortDB();return oldRP.apply(this,arguments)}}
  const oldRC=window.renderClients;if(typeof oldRC==='function'){window.renderClients=function(){sortDB();return oldRC.apply(this,arguments)}}
  const oldRS=window.renderSuppliers;if(typeof oldRS==='function'){window.renderSuppliers=function(){sortDB();return oldRS.apply(this,arguments)}}
}
function setupV6(){style();badge();installSort();professionalTables();installProductEditor();installPurchase();sortDB();if(typeof renderAll==='function')renderAll();}
wait();
})();