(()=>{
'use strict';
const wait=()=>{if(typeof DB==='undefined'||typeof $==='undefined'||typeof num==='undefined'||!document.getElementById('app'))return setTimeout(wait,180);setupV7()};
const esc7=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const saleDate=s=>new Date(s.sold_at||s.created_at||0);
function css(){if($('v7css'))return;const s=document.createElement('style');s.id='v7css';s.textContent=`.v7-head{background:linear-gradient(135deg,#172033,#344054);color:#fff;border-radius:14px;padding:16px;margin:16px 0}.v7-head h3{margin:0 0 5px}.v7-head p{margin:0;opacity:.8}.v7-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:12px 0}.v7-kpi{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px}.v7-kpi small{color:#667085}.v7-kpi b{display:block;font-size:20px;margin-top:5px}.v7-tools{display:flex;gap:8px;flex-wrap:wrap}.v7-client{cursor:pointer;color:#1d4ed8;font-weight:700}.v7-modalbg{position:fixed;inset:0;background:#0008;z-index:10000;display:grid;place-items:center;padding:16px}.v7-modal{width:min(850px,100%);max-height:90vh;overflow:auto;background:white;border-radius:16px;padding:20px}.v7-table{width:100%;border-collapse:collapse}.v7-table td,.v7-table th{padding:8px;border-bottom:1px solid #eee;text-align:left}.v7-alert{background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:10px;margin:8px 0}@media(max-width:800px){.v7-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.v7-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function metrics(){const sales=DB.sales||[],items=DB.sale_items||[];let revenue=0,cost=0;for(const s of sales){revenue+=num(s.total);for(const i of items.filter(x=>String(x.sale_id)===String(s.id))){const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));cost+=num(i.quantity)*num(i.unit_cost??p?.cost)}}return{revenue,cost,profit:revenue-cost,margin:revenue?100*(revenue-cost)/revenue:0}}
function clientStats(){const map={};for(const s of DB.sales||[]){const key=String(s.client_id||s.client_name||'Balcão');if(!map[key])map[key]={id:s.client_id,name:s.client_name||'Cliente balcão',total:0,count:0,last:null};map[key].total+=num(s.total);map[key].count++;const d=saleDate(s);if(!map[key].last||d>map[key].last)map[key].last=d}return Object.values(map).sort((a,b)=>b.total-a.total)}
function addDashboard(){const dash=$('dashboard');if(!dash||$('v7Insights'))return;const m=metrics(),cs=clientStats();const wrap=document.createElement('div');wrap.id='v7Insights';wrap.innerHTML=`<div class="v7-head"><h3>📈 Gestão Profissional V7</h3><p>Indicadores comerciais, clientes e segurança dos dados</p></div><div class="panel"><div class="sectiontitle"><h3>Visão gerencial</h3><div class="v7-tools"><button class="btn alt sm" id="v7Export">⬇ Exportar backup</button><button class="btn alt sm" id="v7CSV">📊 Relatório CSV</button></div></div><div class="v7-grid"><div class="v7-kpi"><small>Lucro bruto acumulado</small><b>${money(m.profit)}</b></div><div class="v7-kpi"><small>Margem bruta</small><b>${m.margin.toFixed(1)}%</b></div><div class="v7-kpi"><small>Clientes compradores</small><b>${cs.length}</b></div><div class="v7-kpi"><small>Melhor cliente</small><b>${esc7(cs[0]?.name||'—')}</b></div></div><div class="two"><div><h4>🏆 Ranking de clientes</h4><div id="v7Ranking"></div></div><div><h4>🔔 Clientes sem comprar há 30+ dias</h4><div id="v7Inactive"></div></div></div></div>`;const first=dash.querySelector('.filterbar');if(first)first.insertAdjacentElement('afterend',wrap);else dash.prepend(wrap);$('v7Export').onclick=exportBackup;$('v7CSV').onclick=exportCSV;renderInsights()}
function renderInsights(){const cs=clientStats();const rank=$('v7Ranking'),inactive=$('v7Inactive');if(rank)rank.innerHTML='<table class="v7-table"><tr><th>Cliente</th><th>Compras</th><th>Total</th></tr>'+cs.slice(0,10).map(c=>`<tr><td><span class="v7-client" onclick="v7ClientHistory('${String(c.id||'').replace(/'/g,'')}','${encodeURIComponent(c.name)}')">${esc7(c.name)}</span></td><td>${c.count}</td><td>${money(c.total)}</td></tr>`).join('')+'</table>';const cut=Date.now()-30*86400000,arr=cs.filter(c=>c.last&&c.last.getTime()<cut).slice(0,10);if(inactive)inactive.innerHTML=arr.length?arr.map(c=>`<div class="v7-alert"><b>${esc7(c.name)}</b><br><small>Última compra: ${c.last.toLocaleDateString('pt-BR')} • Total histórico: ${money(c.total)}</small></div>`).join(''):'<span class="muted">Nenhum cliente nessa condição.</span>'}
window.v7ClientHistory=function(id,nameEnc){const name=decodeURIComponent(nameEnc),sales=(DB.sales||[]).filter(s=>id?String(s.client_id)===String(id):String(s.client_name)===name).sort((a,b)=>saleDate(b)-saleDate(a));const d=document.createElement('div');d.className='v7-modalbg';d.innerHTML=`<div class="v7-modal"><div class="sectiontitle"><h3>Histórico — ${esc7(name)}</h3><button class="btn alt" id="v7Close">Fechar</button></div><p><b>${sales.length}</b> venda(s) • Total ${money(sales.reduce((a,s)=>a+num(s.total),0))}</p><table class="v7-table"><tr><th>Data</th><th>Pagamento</th><th>Total</th><th>Observação</th></tr>${sales.map(s=>`<tr><td>${saleDate(s).toLocaleDateString('pt-BR')}</td><td>${esc7(s.payment_method||'-')}</td><td>${money(s.total)}</td><td>${esc7(s.notes||s.observation||'')}</td></tr>`).join('')}</table></div>`;document.body.appendChild(d);d.querySelector('#v7Close').onclick=()=>d.remove()};
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function exportBackup(){const data={exported_at:new Date().toISOString(),version:'V7',products:DB.products||[],clients:DB.clients||[],suppliers:DB.suppliers||[],sales:DB.sales||[],sale_items:DB.sale_items||[],purchases:DB.purchases||[],purchase_items:DB.purchase_items||[],cash_transactions:DB.cash_transactions||[],accounts_payable:DB.accounts_payable||[],accounts_receivable:DB.accounts_receivable||[]};download('alemao-erp-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data,null,2),'application/json')}
function exportCSV(){const rows=[['Data','Cliente','Pagamento','Total','Observacao'],...(DB.sales||[]).sort((a,b)=>saleDate(b)-saleDate(a)).map(s=>[saleDate(s).toLocaleDateString('pt-BR'),s.client_name||'Balcão',s.payment_method||'',num(s.total).toFixed(2).replace('.',','),s.notes||s.observation||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');download('relatorio-vendas-'+new Date().toISOString().slice(0,10)+'.csv','\ufeff'+csv,'text/csv;charset=utf-8')}
function addClientHistoryButtons(){const old=window.renderClients;if(typeof old==='function'&&!old.__v7){const w=function(){const r=old.apply(this,arguments);setTimeout(()=>{document.querySelectorAll('#clientsTable tbody tr').forEach((tr,i)=>{const clients=(DB.clients||[]).filter(c=>String(c.name||'').toLowerCase().includes(String($('clientSearch')?.value||'').toLowerCase())).sort((a,b)=>String(a.name).localeCompare(String(b.name),'pt-BR',{sensitivity:'base'}));const c=clients[i],cell=tr.lastElementChild;if(!c||!cell||cell.querySelector('.v7hist'))return;const b=document.createElement('button');b.className='btn alt sm v7hist';b.textContent='Histórico';b.onclick=()=>v7ClientHistory(c.id,encodeURIComponent(c.name));(cell.querySelector('.actions')||cell).prepend(b)},0);return r};w.__v7=true;window.renderClients=w}}
function setupV7(){css();const b=document.querySelector('.brand small');if(b)b.textContent='ERP V7 • Gestão Profissional';addDashboard();addClientHistoryButtons();if(typeof renderClients==='function')renderClients();setTimeout(addDashboard,1000);setInterval(renderInsights,4000)}wait();
})();