(()=>{
'use strict';
const wait=()=>{if(typeof DB==='undefined'||typeof $==='undefined'||typeof num==='undefined'||!document.getElementById('app'))return setTimeout(wait,200);setup()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=s=>new Date(s.sold_at||s.created_at||0);
function style(){if(document.getElementById('v7style'))return;const s=document.createElement('style');s.id='v7style';s.textContent='.v7head{background:linear-gradient(135deg,#172033,#344054);color:#fff;border-radius:14px;padding:16px;margin:16px 0}.v7head h3{margin:0 0 4px}.v7head p{margin:0;opacity:.8}.v7grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:12px 0}.v7kpi{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px}.v7kpi small{color:#667085}.v7kpi b{display:block;font-size:20px;margin-top:5px}.v7tools{display:flex;gap:8px;flex-wrap:wrap}.v7table{width:100%;border-collapse:collapse}.v7table th,.v7table td{padding:8px;border-bottom:1px solid #eee;text-align:left}.v7link{color:#1d4ed8;font-weight:700;cursor:pointer}.v7alert{background:#fff7ed;border:1px solid #fed7aa;border-radius:10px;padding:10px;margin:8px 0}.v7modalbg{position:fixed;inset:0;background:#0008;z-index:10000;display:grid;place-items:center;padding:16px}.v7modal{width:min(850px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:20px}@media(max-width:800px){.v7grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.v7grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function stats(){const map={};for(const s of DB.sales||[]){const k=String(s.client_id||s.client_name||'Balcao');if(!map[k])map[k]={id:s.client_id,name:s.client_name||'Cliente balcão',total:0,count:0,last:null};map[k].total+=num(s.total);map[k].count++;const d=dt(s);if(!map[k].last||d>map[k].last)map[k].last=d}return Object.values(map).sort((a,b)=>b.total-a.total)}
function financial(){let revenue=0,cost=0;for(const s of DB.sales||[]){revenue+=num(s.total);for(const i of (DB.sale_items||[]).filter(x=>String(x.sale_id)===String(s.id))){const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));cost+=num(i.quantity)*num(p?.cost)}}return{revenue,cost,profit:revenue-cost,margin:revenue?((revenue-cost)/revenue*100):0}}
function addPanel(){const dash=document.getElementById('dashboard');if(!dash||document.getElementById('v7panel'))return;const f=financial(),cs=stats();const p=document.createElement('div');p.id='v7panel';p.innerHTML='<div class="v7head"><h3>📈 Gestão Profissional V7</h3><p>Indicadores comerciais, clientes e segurança dos dados</p></div><div class="panel"><div class="sectiontitle"><h3>Visão gerencial</h3><div class="v7tools"><button class="btn alt sm" id="v7backup">⬇ Exportar backup</button><button class="btn alt sm" id="v7csv">📊 Relatório CSV</button></div></div><div class="v7grid"><div class="v7kpi"><small>Lucro bruto acumulado</small><b>'+money(f.profit)+'</b></div><div class="v7kpi"><small>Margem bruta</small><b>'+f.margin.toFixed(1)+'%</b></div><div class="v7kpi"><small>Clientes compradores</small><b>'+cs.length+'</b></div><div class="v7kpi"><small>Melhor cliente</small><b>'+esc(cs[0]?.name||'—')+'</b></div></div><div class="two"><div><h4>🏆 Ranking de clientes</h4><div id="v7ranking"></div></div><div><h4>🔔 Clientes sem comprar há 30+ dias</h4><div id="v7inactive"></div></div></div></div>';const filter=dash.querySelector('.filterbar');if(filter)filter.insertAdjacentElement('afterend',p);else dash.prepend(p);document.getElementById('v7backup').onclick=backup;document.getElementById('v7csv').onclick=csv;render()}
function render(){const cs=stats(),rank=document.getElementById('v7ranking'),inactive=document.getElementById('v7inactive');if(rank){rank.innerHTML='<table class="v7table"><tr><th>Cliente</th><th>Compras</th><th>Total</th></tr>'+cs.slice(0,10).map(c=>'<tr><td><span class="v7link" data-id="'+esc(c.id||'')+'" data-name="'+encodeURIComponent(c.name)+'">'+esc(c.name)+'</span></td><td>'+c.count+'</td><td>'+money(c.total)+'</td></tr>').join('')+'</table>';rank.querySelectorAll('.v7link').forEach(el=>el.onclick=()=>history(el.dataset.id,el.dataset.name))}const cut=Date.now()-30*86400000,arr=cs.filter(c=>c.last&&c.last.getTime()<cut).slice(0,10);if(inactive)inactive.innerHTML=arr.length?arr.map(c=>'<div class="v7alert"><b>'+esc(c.name)+'</b><br><small>Última compra: '+c.last.toLocaleDateString('pt-BR')+' • Total histórico: '+money(c.total)+'</small></div>').join(''):'<span class="muted">Nenhum cliente nessa condição.</span>'}
function history(id,nameEnc){const name=decodeURIComponent(nameEnc),sales=(DB.sales||[]).filter(s=>id?String(s.client_id)===String(id):String(s.client_name)===name).sort((a,b)=>dt(b)-dt(a));const d=document.createElement('div');d.className='v7modalbg';d.innerHTML='<div class="v7modal"><div class="sectiontitle"><h3>Histórico — '+esc(name)+'</h3><button class="btn alt" id="v7close">Fechar</button></div><p><b>'+sales.length+'</b> venda(s) • Total '+money(sales.reduce((a,s)=>a+num(s.total),0))+'</p><table class="v7table"><tr><th>Data</th><th>Pagamento</th><th>Total</th></tr>'+sales.map(s=>'<tr><td>'+dt(s).toLocaleDateString('pt-BR')+'</td><td>'+esc(s.payment_method||'-')+'</td><td>'+money(s.total)+'</td></tr>').join('')+'</table></div>';document.body.appendChild(d);document.getElementById('v7close').onclick=()=>d.remove()}
function dl(name,text,type){const a=document.createElement('a');const u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(u);a.remove()},500)}
function backup(){const data={exported_at:new Date().toISOString(),products:DB.products||[],clients:DB.clients||[],suppliers:DB.suppliers||[],sales:DB.sales||[],sale_items:DB.sale_items||[],purchases:DB.purchases||[],purchase_items:DB.purchase_items||[],cash_transactions:DB.cash_transactions||[],accounts_payable:DB.accounts_payable||[],accounts_receivable:DB.accounts_receivable||[]};dl('alemao-erp-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(data,null,2),'application/json')}
function csv(){const rows=[['Data','Cliente','Pagamento','Total'],...(DB.sales||[]).sort((a,b)=>dt(b)-dt(a)).map(s=>[dt(s).toLocaleDateString('pt-BR'),s.client_name||'Balcão',s.payment_method||'',num(s.total).toFixed(2).replace('.',',')])];const text='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');dl('relatorio-vendas-'+new Date().toISOString().slice(0,10)+'.csv',text,'text/csv;charset=utf-8')}
function setup(){style();const b=document.querySelector('.brand small');if(b)b.textContent='ERP V7 • Gestão Profissional';addPanel();setTimeout(addPanel,1000);setInterval(render,4000)}
wait();
})();