(()=>{
'use strict';
const wait=()=>{if(typeof DB==='undefined'||typeof $==='undefined'||typeof num==='undefined'||!document.getElementById('app'))return setTimeout(wait,200);setupV8()};
const money8=v=>typeof money==='function'?money(v):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(num(v));
const esc8=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normPhone=v=>String(v||'').replace(/\D/g,'');
const d8=s=>new Date(s?.sold_at||s?.created_at||s?.date||0);
function style8(){if(document.getElementById('v8style'))return;const s=document.createElement('style');s.id='v8style';s.textContent=`
.v8-hero{background:linear-gradient(135deg,#111827,#374151);color:#fff;border-radius:16px;padding:18px;margin-bottom:16px}.v8-hero h2{margin:0 0 5px}.v8-hero p{margin:0;opacity:.8}.v8-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.v8-card{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:14px}.v8-card small{color:#667085}.v8-card b{display:block;font-size:22px;margin-top:5px}.v8-section{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:16px;margin-top:14px}.v8-two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v8-table{width:100%;border-collapse:collapse}.v8-table th,.v8-table td{padding:9px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.v8-bar{height:10px;background:#e5e7eb;border-radius:99px;overflow:hidden;min-width:120px}.v8-bar i{display:block;height:100%;background:#344054}.v8-chip{display:inline-block;padding:4px 8px;border-radius:999px;background:#f2f4f7;font-size:12px}.v8-good{color:#067647;font-weight:700}.v8-warn{color:#b54708;font-weight:700}.v8-actions{display:flex;gap:8px;flex-wrap:wrap}.v8-whatsapp{background:#067647;color:#fff;border:0;border-radius:8px;padding:7px 9px;font-weight:700;cursor:pointer}.v8-filter{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.v8-filter .field{margin:0}.v8-note{font-size:12px;color:#667085;margin-top:8px}
@media(max-width:950px){.v8-grid{grid-template-columns:1fr 1fr}.v8-two{grid-template-columns:1fr}}@media(max-width:560px){.v8-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function addPage(){if(document.getElementById('gestao'))return;const main=document.querySelector('.main');if(!main)return;const sec=document.createElement('section');sec.id='gestao';sec.className='page hidden';sec.innerHTML=`<div class="v8-hero"><h2>🚀 Gestão Pro V8</h2><p>Centro executivo para lucro, produtos, clientes, previsão e cobranças.</p></div><div class="v8-section"><div class="v8-filter"><div class="field"><label>De</label><input id="v8From" type="date"></div><div class="field"><label>Até</label><input id="v8To" type="date"></div><button class="btn" id="v8Apply">Atualizar análise</button><button class="btn alt" id="v8Month">Este mês</button></div></div><div id="v8Kpis" class="v8-grid" style="margin-top:14px"></div><div class="v8-two"><div class="v8-section"><h3>📦 Rentabilidade por produto</h3><div id="v8Products"></div><div class="v8-note">Lucro estimado usando o custo atual cadastrado do produto.</div></div><div class="v8-section"><h3>🏷️ Resultado por categoria</h3><div id="v8Categories"></div></div></div><div class="v8-two"><div class="v8-section"><h3>📈 Evolução dos últimos 6 meses</h3><div id="v8Months"></div></div><div class="v8-section"><h3>🎯 Oportunidades com clientes</h3><div id="v8Clients"></div></div></div><div class="v8-section"><h3>💳 Contas a receber e cobranças</h3><div id="v8Receivables"></div></div>`;main.appendChild(sec);$('v8Apply').onclick=renderV8;$('v8Month').onclick=()=>{const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),1);$('v8From').value=a.toISOString().slice(0,10);$('v8To').value=n.toISOString().slice(0,10);renderV8()};const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),1);$('v8From').value=a.toISOString().slice(0,10);$('v8To').value=n.toISOString().slice(0,10)}
function addNav(){const nav=document.querySelector('.nav');if(!nav||document.getElementById('v8nav'))return;const b=document.createElement('button');b.id='v8nav';b.innerHTML='🚀 Gestão Pro';b.onclick=v8Open;nav.appendChild(b)}
window.v8Open=function(){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));document.getElementById('gestao')?.classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));document.getElementById('v8nav')?.classList.add('active');const t=document.getElementById('title');if(t)t.textContent='Gestão Pro';renderV8()};
function period(){const from=$('v8From')?.value?new Date($('v8From').value+'T00:00:00'):new Date(0),to=$('v8To')?.value?new Date($('v8To').value+'T23:59:59'):new Date();return{from,to}}
function salesPeriod(){const p=period();return (DB.sales||[]).filter(s=>{const d=d8(s);return d>=p.from&&d<=p.to})}
function productAnalytics(sales){const saleIds=new Set(sales.map(s=>String(s.id))),map={};for(const i of DB.sale_items||[]){if(!saleIds.has(String(i.sale_id)))continue;const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));const name=i.product_name||p?.name||'Produto',category=p?.category||'Sem categoria',qty=num(i.quantity),unit=num(i.unit_price??p?.price),cost=num(p?.cost),rev=qty*unit,profit=rev-qty*cost,key=String(i.product_id||name);if(!map[key])map[key]={name,category,qty:0,revenue:0,profit:0};map[key].qty+=qty;map[key].revenue+=rev;map[key].profit+=profit}return Object.values(map).sort((a,b)=>b.profit-a.profit)}
function categoryAnalytics(products){const map={};for(const p of products){const k=p.category||'Sem categoria';if(!map[k])map[k]={name:k,revenue:0,profit:0,qty:0};map[k].revenue+=p.revenue;map[k].profit+=p.profit;map[k].qty+=p.qty}return Object.values(map).sort((a,b)=>b.profit-a.profit)}
function monthly(){const out=[];const now=new Date();for(let x=5;x>=0;x--){const d=new Date(now.getFullYear(),now.getMonth()-x,1),y=d.getFullYear(),m=d.getMonth();const arr=(DB.sales||[]).filter(s=>{const q=d8(s);return q.getFullYear()===y&&q.getMonth()===m});out.push({label:d.toLocaleDateString('pt-BR',{month:'short',year:'2-digit'}),value:arr.reduce((a,s)=>a+num(s.total),0),count:arr.length})}return out}
function clientOpportunities(){const map={};for(const s of DB.sales||[]){const key=String(s.client_id||s.client_name||'balcao');if(!map[key])map[key]={id:s.client_id,name:s.client_name||'Cliente balcão',total:0,last:null};map[key].total+=num(s.total);const ds=d8(s);if(!map[key].last||ds>map[key].last)map[key].last=ds}return Object.values(map).filter(c=>c.id&&c.last).sort((a,b)=>a.last-b.last)}
function clientById(id){return (DB.clients||[]).find(c=>String(c.id)===String(id))}
function waLink(phone,text){let p=normPhone(phone);if(!p)return'';if(p.length<=11)p='55'+p;return'https://wa.me/'+p+'?text='+encodeURIComponent(text)}
function receivables(){return (DB.accounts_receivable||[]).filter(r=>String(r.status||'open').toLowerCase()!=='paid'&&String(r.status||'open').toLowerCase()!=='pago').sort((a,b)=>new Date(a.due_date||0)-new Date(b.due_date||0))}
function renderV8(){if(!$('gestao'))return;const sales=salesPeriod(),revenue=sales.reduce((a,s)=>a+num(s.total),0),prods=productAnalytics(sales),profit=prods.reduce((a,p)=>a+p.profit,0),margin=revenue?profit/revenue*100:0,avgTicket=sales.length?revenue/sales.length:0;const now=new Date(),monthSales=(DB.sales||[]).filter(s=>{const d=d8(s);return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth()}),monthRev=monthSales.reduce((a,s)=>a+num(s.total),0),day=Math.max(1,now.getDate()),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),forecast=monthRev/day*days,recv=receivables().reduce((a,r)=>a+num(r.amount??r.total??r.value),0);$('v8Kpis').innerHTML=[['Faturamento no período',money8(revenue)],['Lucro bruto estimado',money8(profit)],['Margem bruta',margin.toFixed(1)+'%'],['Ticket médio',money8(avgTicket)],['Previsão mês atual',money8(forecast)],['Vendas no período',sales.length],['A receber em aberto',money8(recv)],['Produto mais lucrativo',esc8(prods[0]?.name||'—')]].map(x=>`<div class="v8-card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('');renderProducts(prods);renderCategories(categoryAnalytics(prods));renderMonths();renderClients();renderReceivables()}
function renderProducts(arr){const el=$('v8Products');if(!el)return;if(!arr.length){el.innerHTML='<span class="muted">Sem vendas no período.</span>';return}el.innerHTML='<div class="tablewrap"><table class="v8-table"><tr><th>Produto</th><th>Qtd.</th><th>Receita</th><th>Lucro</th><th>Margem</th></tr>'+arr.slice(0,12).map(p=>`<tr><td>${esc8(p.name)}</td><td>${p.qty.toFixed(2).replace('.00','')}</td><td>${money8(p.revenue)}</td><td class="${p.profit>=0?'v8-good':'badtext'}">${money8(p.profit)}</td><td>${p.revenue?(p.profit/p.revenue*100).toFixed(1):'0.0'}%</td></tr>`).join('')+'</table></div>'}
function renderCategories(arr){const el=$('v8Categories');if(!el)return;if(!arr.length){el.innerHTML='<span class="muted">Sem dados no período.</span>';return}const max=Math.max(...arr.map(x=>x.revenue),1);el.innerHTML='<table class="v8-table"><tr><th>Categoria</th><th>Receita</th><th>Lucro</th><th>Participação</th></tr>'+arr.map(c=>`<tr><td>${esc8(c.name)}</td><td>${money8(c.revenue)}</td><td>${money8(c.profit)}</td><td><div class="v8-bar"><i style="width:${Math.max(2,c.revenue/max*100).toFixed(1)}%"></i></div></td></tr>`).join('')+'</table>'}
function renderMonths(){const el=$('v8Months');if(!el)return;const arr=monthly(),max=Math.max(...arr.map(x=>x.value),1);el.innerHTML='<table class="v8-table"><tr><th>Mês</th><th>Vendas</th><th>Faturamento</th><th>Evolução</th></tr>'+arr.map(x=>`<tr><td>${esc8(x.label)}</td><td>${x.count}</td><td>${money8(x.value)}</td><td><div class="v8-bar"><i style="width:${Math.max(2,x.value/max*100).toFixed(1)}%"></i></div></td></tr>`).join('')+'</table>'}
function renderClients(){const el=$('v8Clients');if(!el)return;const cut=Date.now()-30*86400000,arr=clientOpportunities().filter(c=>c.last.getTime()<cut).slice(0,10);if(!arr.length){el.innerHTML='<span class="muted">Nenhuma oportunidade de reativação agora.</span>';return}el.innerHTML=arr.map(c=>{const cl=clientById(c.id),days=Math.floor((Date.now()-c.last.getTime())/86400000),link=waLink(cl?.phone,`Olá ${c.name}! Tudo bem? Aqui é do Alemão Produtos da Roça. Sentimos sua falta e estamos à disposição para sua próxima encomenda.`);return`<div class="v7alert"><b>${esc8(c.name)}</b><br><small>${days} dias sem comprar • Histórico ${money8(c.total)}</small>${link?`<div style="margin-top:7px"><button class="v8-whatsapp" onclick="window.open('${link}','_blank')">WhatsApp</button></div>`:''}</div>`}).join('')}
function renderReceivables(){const el=$('v8Receivables');if(!el)return;const arr=receivables();if(!arr.length){el.innerHTML='<span class="muted">Nenhuma conta a receber em aberto.</span>';return}const today=new Date();el.innerHTML='<div class="tablewrap"><table class="v8-table"><tr><th>Cliente/Descrição</th><th>Vencimento</th><th>Valor</th><th>Status</th><th>Ação</th></tr>'+arr.slice(0,30).map(r=>{const client=(DB.clients||[]).find(c=>String(c.id)===String(r.client_id))||(DB.clients||[]).find(c=>String(c.name||'').toLowerCase()===String(r.client_name||r.description||'').toLowerCase()),name=r.client_name||client?.name||r.description||'Conta a receber',due=r.due_date?new Date(r.due_date+'T12:00:00'):null,late=due&&due<today,amount=num(r.amount??r.total??r.value),link=waLink(client?.phone,`Olá ${name}! Passando para lembrar do valor de ${money8(amount)}${r.due_date?' com vencimento em '+due.toLocaleDateString('pt-BR'):''}. Qualquer dúvida, estamos à disposição. Alemão Produtos da Roça.`);return`<tr><td>${esc8(name)}</td><td>${due?due.toLocaleDateString('pt-BR'):'—'}</td><td>${money8(amount)}</td><td><span class="${late?'v8-warn':'v8-chip'}">${late?'Vencida':'Em aberto'}</span></td><td>${link?`<button class="v8-whatsapp" onclick="window.open('${link}','_blank')">Cobrar</button>`:'—'}</td></tr>`}).join('')+'</table></div>'}
function setupV8(){style8();addPage();addNav();const b=document.querySelector('.brand small');if(b)b.textContent='ERP V8 • Gestão Pro';const oldLoad=window.load;if(typeof oldLoad==='function'&&!oldLoad.__v8){const w=async function(){const r=await oldLoad.apply(this,arguments);setTimeout(()=>{if(!$('gestao')?.classList.contains('hidden'))renderV8()},50);return r};w.__v8=true;window.load=w}}
wait();
})();