(()=>{
'use strict';
const wait=()=>{if(typeof DB==='undefined'||typeof $==='undefined'||typeof num==='undefined'||!document.getElementById('app'))return setTimeout(wait,220);setupV9()};
const m9=v=>typeof money==='function'?money(v):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(num(v));
const e9=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date9=x=>new Date(x?.sold_at||x?.purchased_at||x?.date||x?.created_at||0);
const ym=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');
function css(){if($('v9css'))return;const s=document.createElement('style');s.id='v9css';s.textContent=`.v9hero{background:linear-gradient(135deg,#0f172a,#334155);color:#fff;border-radius:16px;padding:18px;margin-bottom:16px}.v9hero h2{margin:0 0 5px}.v9hero p{margin:0;opacity:.8}.v9grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.v9card,.v9section{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:15px}.v9section{margin-top:14px}.v9card small{color:#667085}.v9card b{display:block;font-size:22px;margin-top:5px}.v9two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.v9table{width:100%;border-collapse:collapse}.v9table th,.v9table td{padding:9px;border-bottom:1px solid #eee;text-align:left;font-size:13px}.v9progress{height:12px;border-radius:99px;background:#e5e7eb;overflow:hidden}.v9progress i{display:block;height:100%;background:#334155}.v9alert{padding:11px;border-radius:10px;margin:8px 0;border:1px solid #e5e7eb}.v9alert.warn{background:#fff7ed;border-color:#fed7aa}.v9alert.good{background:#ecfdf3;border-color:#abefc6}.v9alert.bad{background:#fef3f2;border-color:#fecdca}.v9form{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;align-items:end}.v9note{font-size:12px;color:#667085;margin-top:7px}.v9pill{display:inline-block;padding:4px 8px;border-radius:999px;background:#f2f4f7;font-size:12px}.v9strong{font-weight:800}@media(max-width:950px){.v9grid,.v9form{grid-template-columns:1fr 1fr}.v9two{grid-template-columns:1fr}}@media(max-width:560px){.v9grid,.v9form{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function addPage(){if($('planejamento'))return;const main=document.querySelector('.main');if(!main)return;const sec=document.createElement('section');sec.id='planejamento';sec.className='page hidden';sec.innerHTML=`<div class="v9hero"><h2>🧠 Gestão Estratégica V9</h2><p>Metas, orçamento, DRE gerencial, fluxo de caixa projetado e alertas de decisão.</p></div><div class="v9section"><h3>🎯 Metas do mês</h3><div class="v9form"><div class="field"><label>Meta de faturamento (R$)</label><input id="v9GoalRevenue" type="number" step="0.01" min="0"></div><div class="field"><label>Meta de lucro (R$)</label><input id="v9GoalProfit" type="number" step="0.01" min="0"></div><div class="field"><label>Orçamento de despesas (R$)</label><input id="v9BudgetExpense" type="number" step="0.01" min="0"></div><div><button class="btn" id="v9SaveGoals">Salvar metas</button></div></div><div id="v9GoalStatus" style="margin-top:12px"></div></div><div id="v9Kpis" class="v9grid" style="margin-top:14px"></div><div class="v9two"><div class="v9section"><h3>📑 DRE gerencial do mês</h3><div id="v9Dre"></div><div class="v9note">Visão gerencial estimada: custos de produtos usam o custo atual cadastrado.</div></div><div class="v9section"><h3>💧 Fluxo de caixa projetado</h3><div id="v9Cashflow"></div><div class="v9note">Projeção considera saldo atual, contas a receber e contas a pagar em aberto.</div></div></div><div class="v9two"><div class="v9section"><h3>📊 Comparação mês a mês</h3><div id="v9Compare"></div></div><div class="v9section"><h3>🚨 Alertas de gestão</h3><div id="v9Alerts"></div></div></div><div class="v9section"><h3>💡 Sugestões de decisão</h3><div id="v9Suggestions"></div></div>`;main.appendChild(sec);$('v9SaveGoals').onclick=saveGoals;loadGoals()}
function addNav(){const nav=document.querySelector('.nav');if(!nav||$('v9nav'))return;const b=document.createElement('button');b.id='v9nav';b.innerHTML='🧠 Gestão Estratégica';b.onclick=openV9;nav.appendChild(b)}
window.openV9=function(){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$('planejamento')?.classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));$('v9nav')?.classList.add('active');if($('title'))$('title').textContent='Gestão Estratégica';renderV9()};
function settingsKey(){const d=new Date();return'erp_v9_goals_'+ym(d)}
function loadGoals(){let g={revenue:0,profit:0,expense:0};try{g=JSON.parse(localStorage.getItem(settingsKey())||'{}')}catch{};$('v9GoalRevenue').value=num(g.revenue)||'';$('v9GoalProfit').value=num(g.profit)||'';$('v9BudgetExpense').value=num(g.expense)||''}
function saveGoals(){const g={revenue:num($('v9GoalRevenue').value),profit:num($('v9GoalProfit').value),expense:num($('v9BudgetExpense').value)};localStorage.setItem(settingsKey(),JSON.stringify(g));renderV9();if(typeof msg==='function')msg('Metas e orçamento salvos para este mês.')}
function getGoals(){try{return JSON.parse(localStorage.getItem(settingsKey())||'{}')}catch{return{}}}
function monthSales(offset=0){const n=new Date(),d=new Date(n.getFullYear(),n.getMonth()+offset,1),y=d.getFullYear(),m=d.getMonth();return(DB.sales||[]).filter(s=>{const x=date9(s);return x.getFullYear()===y&&x.getMonth()===m})}
function monthPurchases(offset=0){const n=new Date(),d=new Date(n.getFullYear(),n.getMonth()+offset,1),y=d.getFullYear(),m=d.getMonth();return(DB.purchases||[]).filter(p=>{const x=date9(p);return x.getFullYear()===y&&x.getMonth()===m})}
function monthCash(offset=0){const n=new Date(),d=new Date(n.getFullYear(),n.getMonth()+offset,1),y=d.getFullYear(),m=d.getMonth();return(DB.cash_transactions||[]).filter(t=>{const x=date9(t);return x.getFullYear()===y&&x.getMonth()===m})}
function saleCost(sales){const ids=new Set(sales.map(s=>String(s.id)));let cost=0;for(const i of DB.sale_items||[]){if(!ids.has(String(i.sale_id)))continue;const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));cost+=num(i.quantity)*num(i.unit_cost??p?.cost)}return cost}
function calc(offset=0){const sales=monthSales(offset),revenue=sales.reduce((a,s)=>a+num(s.total),0),cogs=saleCost(sales),gross=revenue-cogs,cash=monthCash(offset),manualOut=cash.filter(t=>String(t.type||'').toLowerCase()==='out').reduce((a,t)=>a+num(t.amount??t.value??t.total),0),manualIn=cash.filter(t=>String(t.type||'').toLowerCase()==='in').reduce((a,t)=>a+num(t.amount??t.value??t.total),0),purchases=monthPurchases(offset).reduce((a,p)=>a+num(p.total),0),expenses=Math.max(manualOut,purchases),net=gross-expenses,margin=revenue?net/revenue*100:0;return{sales,revenue,cogs,gross,expenses,net,margin,manualIn,manualOut,purchases}}
function openReceivables(){return(DB.accounts_receivable||[]).filter(r=>!['paid','pago'].includes(String(r.status||'open').toLowerCase()))}
function openPayables(){return(DB.accounts_payable||[]).filter(r=>!['paid','pago'].includes(String(r.status||'open').toLowerCase()))}
function cashBalance(){return(DB.cash_transactions||[]).reduce((a,t)=>{const v=num(t.amount??t.value??t.total),typ=String(t.type||'').toLowerCase();return a+(typ==='out'?-v:v)},0)}
function renderGoals(cur,g){const revGoal=num(g.revenue),profitGoal=num(g.profit),expBudget=num(g.expense),revPct=revGoal?Math.min(100,cur.revenue/revGoal*100):0,profPct=profitGoal?Math.min(100,cur.net/profitGoal*100):0,expPct=expBudget?cur.expenses/expBudget*100:0;$('v9GoalStatus').innerHTML=`<div class="v9grid"><div><small>Faturamento</small><div class="v9progress"><i style="width:${revPct.toFixed(1)}%"></i></div><div class="v9note">${m9(cur.revenue)} de ${revGoal?m9(revGoal):'meta não definida'} (${revPct.toFixed(1)}%)</div></div><div><small>Lucro</small><div class="v9progress"><i style="width:${Math.max(0,profPct).toFixed(1)}%"></i></div><div class="v9note">${m9(cur.net)} de ${profitGoal?m9(profitGoal):'meta não definida'} (${profPct.toFixed(1)}%)</div></div><div><small>Despesas</small><div class="v9progress"><i style="width:${Math.min(100,Math.max(0,expPct)).toFixed(1)}%"></i></div><div class="v9note">${m9(cur.expenses)} de ${expBudget?m9(expBudget):'orçamento não definido'} ${expBudget?'('+expPct.toFixed(1)+'%)':''}</div></div></div>`}
function renderKpis(cur,prev){const trend=prev.revenue?((cur.revenue-prev.revenue)/prev.revenue*100):0,recv=openReceivables().reduce((a,r)=>a+num(r.amount??r.total??r.value),0),pay=openPayables().reduce((a,r)=>a+num(r.amount??r.total??r.value),0),projected=cashBalance()+recv-pay;$('v9Kpis').innerHTML=[['Faturamento mês',m9(cur.revenue)],['Resultado líquido estimado',m9(cur.net)],['Margem líquida estimada',cur.margin.toFixed(1)+'%'],['Variação vs. mês anterior',(trend>=0?'+':'')+trend.toFixed(1)+'%'],['Contas a receber',m9(recv)],['Contas a pagar',m9(pay)],['Caixa projetado',m9(projected)],['Vendas no mês',cur.sales.length]].map(x=>`<div class="v9card"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function renderDre(cur){$('v9Dre').innerHTML=`<table class="v9table"><tr><td>Receita bruta</td><td class="v9strong">${m9(cur.revenue)}</td></tr><tr><td>(-) Custo dos produtos vendidos</td><td>${m9(cur.cogs)}</td></tr><tr><td>= Lucro bruto</td><td class="v9strong">${m9(cur.gross)}</td></tr><tr><td>(-) Despesas/saídas operacionais</td><td>${m9(cur.expenses)}</td></tr><tr><td>= Resultado líquido estimado</td><td class="v9strong">${m9(cur.net)}</td></tr><tr><td>Margem líquida estimada</td><td>${cur.margin.toFixed(1)}%</td></tr></table>`}
function renderCashflow(){const bal=cashBalance(),recv=openReceivables(),pay=openPayables(),rv=recv.reduce((a,r)=>a+num(r.amount??r.total??r.value),0),pv=pay.reduce((a,r)=>a+num(r.amount??r.total??r.value),0),proj=bal+rv-pv;$('v9Cashflow').innerHTML=`<table class="v9table"><tr><td>Saldo atual do caixa</td><td>${m9(bal)}</td></tr><tr><td>(+) A receber em aberto</td><td>${m9(rv)}</td></tr><tr><td>(-) A pagar em aberto</td><td>${m9(pv)}</td></tr><tr><td>= Saldo projetado</td><td class="v9strong">${m9(proj)}</td></tr></table><div class="v9note">${proj<0?'⚠️ Projeção negativa: atenção ao caixa.':'✅ Projeção de caixa positiva.'}</div>`}
function renderCompare(cur,prev){const rows=[['Faturamento',cur.revenue,prev.revenue],['Lucro bruto',cur.gross,prev.gross],['Despesas',cur.expenses,prev.expenses],['Resultado líquido',cur.net,prev.net]];$('v9Compare').innerHTML='<table class="v9table"><tr><th>Indicador</th><th>Mês atual</th><th>Mês anterior</th><th>Variação</th></tr>'+rows.map(r=>{const v=r[2]?((r[1]-r[2])/Math.abs(r[2])*100):0;return`<tr><td>${r[0]}</td><td>${m9(r[1])}</td><td>${m9(r[2])}</td><td>${(v>=0?'+':'')+v.toFixed(1)}%</td></tr>`}).join('')+'</table>'}
function renderAlerts(cur,g){const alerts=[],revGoal=num(g.revenue),expBudget=num(g.expense),low=(DB.products||[]).filter(p=>num(p.stock)<=num(p.min_stock));if(revGoal&&cur.revenue<revGoal*.5&&new Date().getDate()>15)alerts.push(['warn','Meta de faturamento abaixo de 50% após metade do mês.']);if(expBudget&&cur.expenses>expBudget)alerts.push(['bad','Despesas acima do orçamento mensal definido.']);if(cur.net<0)alerts.push(['bad','Resultado líquido estimado está negativo neste mês.']);if(openPayables().some(p=>p.due_date&&new Date(p.due_date+'T23:59:59')<new Date()))alerts.push(['warn','Existem contas a pagar vencidas.']);if(low.length)alerts.push(['warn',low.length+' produto(s) estão no estoque mínimo ou abaixo.']);if(!alerts.length)alerts.push(['good','Nenhum alerta crítico identificado agora.']);$('v9Alerts').innerHTML=alerts.map(a=>`<div class="v9alert ${a[0]}">${a[1]}</div>`).join('')}
function renderSuggestions(cur,prev,g){const out=[];const products={};for(const i of DB.sale_items||[]){const p=(DB.products||[]).find(x=>String(x.id)===String(i.product_id));if(!p)continue;const q=num(i.quantity),rev=q*num(i.unit_price??p.price),prof=rev-q*num(p.cost);if(!products[p.id])products[p.id]={name:p.name,rev:0,prof:0,q:0};products[p.id].rev+=rev;products[p.id].prof+=prof;products[p.id].q+=q}const arr=Object.values(products).sort((a,b)=>b.prof-a.prof);if(arr[0])out.push('Priorize divulgação e disponibilidade de <b>'+e9(arr[0].name)+'</b>, atualmente entre os produtos com maior contribuição estimada de lucro.');if(prev.revenue>0&&cur.revenue<prev.revenue*.85)out.push('O faturamento está mais de 15% abaixo do mês anterior; vale reforçar reativação de clientes e campanhas de recompra.');if(cur.margin<10&&cur.revenue>0)out.push('A margem líquida estimada está baixa. Revise preços, custo de compra, frete e despesas antes de aumentar volume.');if(openReceivables().length)out.push('Há valores a receber em aberto. Priorize cobrança dos vencidos para proteger o caixa.');if(num(g.revenue)>0&&cur.revenue>=num(g.revenue))out.push('A meta de faturamento foi atingida. Considere preservar margem e caixa em vez de conceder descontos agressivos.');if(!out.length)out.push('Continue registrando compras, vendas e despesas com consistência; isso melhora a qualidade das recomendações gerenciais.');$('v9Suggestions').innerHTML=out.map((x,i)=>`<div class="v9alert good"><b>${i+1}.</b> ${x}</div>`).join('')}
function renderV9(){if(!$('planejamento'))return;const cur=calc(0),prev=calc(-1),g=getGoals();renderGoals(cur,g);renderKpis(cur,prev);renderDre(cur);renderCashflow();renderCompare(cur,prev);renderAlerts(cur,g);renderSuggestions(cur,prev,g)}
function setupV9(){css();addPage();addNav();const b=document.querySelector('.brand small');if(b)b.textContent='ERP V9 • Gestão Estratégica';const oldLoad=window.load;if(typeof oldLoad==='function'&&!oldLoad.__v9){const w=async function(){const r=await oldLoad.apply(this,arguments);setTimeout(()=>{if(!$('planejamento')?.classList.contains('hidden'))renderV9()},80);return r};w.__v9=true;window.load=w}}
wait();
})();